library(tidyverse)
library(knitr)
library(gridExtra)
library(jpeg)
library(png)
library(lubridate)
library(pacman)
library(stringr)
library(ggpubr)
library(tableone)
library(Publish)
library(officer)
library(readxl)
library(styler)
library(data.table)
library(bannerCommenter)
library(survminer)
library(survival)
library(prodlim)
library(scales)

get_time <- function(){
  format(Sys.time(), "%d%m%y h%H m%M s%S %Z")
}